# Generated by Django 5.2.3 on 2025-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('quality', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
            ],
        ),
    ]
