# Generated by Django 5.2.3 on 2025-06-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
