# Generated by Django 5.2.3 on 2025-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkmain', '0003_dailyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='milk_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
